### ISSUE TITLE
Disable Pollinate

### ISSUE THREAD

**Issue by sarciszewski** [micahflee/fixubuntu#34]
https://wiki.ubuntu.com/Security/Features#prng-cloud

Pollinate (getting entropy over the network) is NOT a good idea. While we're fixing Ubuntu, we should remove this potential RNG vulnerability.
 
Refer to this article: http://www.lothar.com/blog/48-remote-entropy/

**Comment by kanoi** [comment]
It is enabled by default in Ubuntu 18.04.2 LTS
