### ISSUE TITLE
Video suggestions still working

### ISSUE THREAD

**Issue by anonymouz** [micahflee/fixubuntu#43]
After using the **fixubuntu.sh** script I noticed that the video button in the dash still produced suggestions in 14.04. Some searching around I found that this is handled by the "unity-scope-video-remote" package. This package has been around sinds 12.04 upto 14.10, see:

http://packages.ubuntu.com/search?keywords=unity-scope-video-remote&searchon=names&suite=all&section=all

I fixed this bug by running:

```
sudo apt-get purge unity-scope-video-remote 
```

Could you fix the "fixubuntu.sh" script to remove the video suggestions!?

Thanks for the great work!

Regards,
Onno

**Comment by micahflee** [comment]
I just replaces fixubuntu.sh with GUI instructions (#44). Does this still apply?

**Comment by anonymouz** [comment]
I'll check it
