### ISSUE TITLE
Replace fixubuntu.sh with graphical instructions

### ISSUE THREAD

**Issue by micahflee** [micahflee/fixubuntu#44]
It looks like since Fix Ubuntu launched Ubuntu has ironed out a lot of its obnoxious problems. I want to confirm, but I think that by opening System Settings > Security & Privacy, going to the Search tab and turning off "Include online search results", none of your dash search queries leave your computer.

If this is the case, then I want to redesign the website and replace the script to run with simple instructions for how to turn this off in the GUI.

**Comment by micahflee** [comment]
Finally got around to this! Thank you @anonymouz for the help.

**Comment by brendan-r** [comment]
For people who maintain set-up scripts (e.g. in a dotfiles type repo), `fixubuntu.sh` is a fantastic resource.

Is it possible that it could be made available again? Do you no longer wish to maintain it?

**Comment by micahflee** [comment]
@brendan-R the old fixubuntu.sh script is available in the git history. It looks like this is the most recent version: https://github.com/micahflee/fixubuntu/blob/47e6b66eca09688212b8229fa98c21062fd27cef/fixubuntu.sh

And yes, one of the main reasons why I switched from a script to GUI instructions is because I don't want to keep maintaining the script, and it breaks or requires adjustments with every new Ubuntu release.

**Comment by brendan-r** [comment]
Got it, thanks!
