### ISSUE TITLE
./fixubuntu.sh: line 9: [[: 14.04: syntax error: invalid arithmetic operator (error token is ".04")

### ISSUE THREAD

**Issue by adrinjalali** [micahflee/fixubuntu#50]
Hi,
Nice job.
How can we fix this?

$ ./fixubuntu.sh 
./fixubuntu.sh: line 9: [[: 14.04: syntax error: invalid arithmetic operator (error token is ".04")
./fixubuntu.sh: line 9: [[: 14.04: syntax error: invalid arithmetic operator (error token is ".04")
All done. Enjoy your privacy.

$ /usr/bin/lsb_release -rs
14.04

**Comment by XhmikosR** [comment]
Isn't this already fixed?

**Comment by webmaster128** [comment]
Jap, this one can be closed. It is covered by https://github.com/micahflee/fixubuntu/pull/53/files

**Comment by micahflee** [comment]
This issue no longer applies after #44. There's no longer a `fixubuntu.sh`.
