### ISSUE TITLE
Current commit is not live

### ISSUE THREAD

**Issue by JHGitty** [micahflee/fixubuntu#67]
The last commit was 18 days ago.
The current sourcecode of http://fixubuntu.com contains:
```<html lang=en>```

The code in this repository contains:
```<html lang="en">```

This is not the same. Why?

**Comment by micahflee** [comment]
I think grunt strips the quotes. I just confirmed that the server is indeed using the latest commit, and re-ran `grunt build`, and the resulting index.html says `<html lang=en>`.
